// <auto-generated />
using System;
using Intrega.Modulos.Roteirizacao.Infraestrutura;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Intrega.Modulos.Roteirizacao.Infraestrutura.Migracoes
{
    [DbContext(typeof(ContextoRoteirizacao))]
    partial class ContextoRoteirizacaoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("roteirizacao")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Intrega.Modulos.Roteirizacao.Dominio.Rota", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AlgoritmoUsado")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ConcluidaEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date");

                    b.Property<string>("DescricaoDaChegada")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("DescricaoDaSaida")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<double>("DistanciaTotalMetros")
                        .HasColumnType("double precision");

                    b.Property<Guid>("DonoId")
                        .HasColumnType("uuid");

                    b.Property<double>("DuracaoTotalSegundos")
                        .HasColumnType("double precision");

                    b.Property<Guid>("EntregadorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Geometria")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("HorarioPlanejadoDeSaida")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("IniciadaEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("LatitudeDeChegada")
                        .HasColumnType("double precision");

                    b.Property<double>("LatitudeDeSaida")
                        .HasColumnType("double precision");

                    b.Property<double?>("LongitudeDeChegada")
                        .HasColumnType("double precision");

                    b.Property<double>("LongitudeDeSaida")
                        .HasColumnType("double precision");

                    b.Property<string>("MotorUsado")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid?>("OrganizacaoId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("OtimizadaEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Recalculos")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("SaidaConsiderada")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Veiculo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<uint>("Versao")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<bool>("VoltarAoInicio")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("DonoId", "Data");

                    b.HasIndex("EntregadorId", "Data");

                    b.HasIndex("OrganizacaoId", "Data");

                    b.ToTable("rotas", "roteirizacao");
                });

            modelBuilder.Entity("Intrega.Modulos.Roteirizacao.Dominio.Rota", b =>
                {
                    b.OwnsMany("Intrega.Modulos.Roteirizacao.Dominio.ItemDaSequencia", "Sequencia", b1 =>
                        {
                            b1.Property<Guid>("RotaId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<int>("AtendimentoSegundos");

                            b1.Property<bool>("AtrasadaParaJanela");

                            b1.Property<double>("ChegadaAposSaidaSegundos");

                            b1.Property<double>("DistanciaDoTrechoMetros");

                            b1.Property<double>("DuracaoDoTrechoSegundos");

                            b1.Property<int>("Ordem");

                            b1.Property<Guid>("ParadaId");

                            b1.Property<DateTimeOffset>("PrevisaoDeChegada");

                            b1.HasKey("RotaId", "__synthesizedOrdinal");

                            b1.ToTable("rotas", "roteirizacao");

                            b1
                                .ToJson("sequencia")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("RotaId");
                        });

                    b.Navigation("Sequencia");
                });
#pragma warning restore 612, 618
        }
    }
}
