// <auto-generated />
using System;
using System.Collections.Generic;
using Intrega.Modulos.Paradas.Infraestrutura;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Intrega.Modulos.Paradas.Infraestrutura.Migracoes
{
    [DbContext(typeof(ContextoParadas))]
    [Migration("20261006210544_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("paradas")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Intrega.Modulos.Paradas.Dominio.Parada", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CaminhoDoComprovante")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.PrimitiveCollection<List<string>>("CodigosDePacote")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<double?>("ConfiancaDaLocalizacao")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("EntregueEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EstrategiaDeNovaTentativa")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<TimeOnly?>("JanelaFim")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly?>("JanelaInicio")
                        .HasColumnType("time without time zone");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("LatitudeDaEntrega")
                        .HasColumnType("double precision");

                    b.Property<bool>("LocalConfirmado")
                        .HasColumnType("boolean");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("LongitudeDaEntrega")
                        .HasColumnType("double precision");

                    b.Property<string>("Marketplace")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("NomeDoDestinatario")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("NovaTentativaApos")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text");

                    b.Property<string>("ObservacoesDaEntrega")
                        .HasColumnType("text");

                    b.Property<Guid?>("OrganizacaoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("Prioridade")
                        .HasColumnType("integer");

                    b.Property<string>("ProvedorDaLocalizacao")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("QuantidadeDePacotes")
                        .HasColumnType("integer");

                    b.Property<string>("RecebidoPor")
                        .HasColumnType("text");

                    b.Property<Guid>("ResponsavelId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RotaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TelefoneDoDestinatario")
                        .HasColumnType("text");

                    b.Property<int>("TempoDeAtendimentoSegundos")
                        .HasColumnType("integer");

                    b.Property<int>("Tentativas")
                        .HasColumnType("integer");

                    b.Property<string>("UltimoMotivoDeFalha")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("CodigosDePacote");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("CodigosDePacote"), "gin");

                    b.HasIndex("RotaId");

                    b.HasIndex("OrganizacaoId", "Status");

                    b.HasIndex("ResponsavelId", "Status");

                    b.ToTable("paradas", "paradas");
                });

            modelBuilder.Entity("Intrega.Modulos.Paradas.Dominio.Parada", b =>
                {
                    b.OwnsOne("Intrega.Modulos.Paradas.Dominio.EnderecoDaParada", "Endereco", b1 =>
                        {
                            b1.Property<Guid>("ParadaId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Bairro")
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("bairro");

                            b1.Property<string>("Cep")
                                .HasMaxLength(8)
                                .HasColumnType("character varying(8)")
                                .HasColumnName("cep");

                            b1.Property<string>("Cidade")
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("cidade");

                            b1.Property<string>("Complemento")
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("complemento");

                            b1.Property<string>("Descricao")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("descricao");

                            b1.Property<string>("Logradouro")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("logradouro");

                            b1.Property<string>("Numero")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("numero");

                            b1.Property<string>("Uf")
                                .HasMaxLength(2)
                                .HasColumnType("character varying(2)")
                                .HasColumnName("uf");

                            b1.HasKey("ParadaId");

                            b1.ToTable("paradas", "paradas");

                            b1.WithOwner()
                                .HasForeignKey("ParadaId");
                        });

                    b.Navigation("Endereco")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
