<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="Microsoft.Extensions.Identity.Core" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" PrivateAssets="all" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\Compartilhado\Intrega.Infraestrutura\Intrega.Infraestrutura.csproj" />
    <ProjectReference Include="..\Intrega.Modulos.Identidade.Contratos\Intrega.Modulos.Identidade.Contratos.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Intrega.TestesUnitarios" />
  </ItemGroup>
</Project>
