<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\..\..\Compartilhado\Intrega.Infraestrutura\Intrega.Infraestrutura.csproj" />
    <ProjectReference Include="..\..\Paradas\Intrega.Modulos.Paradas.Contratos\Intrega.Modulos.Paradas.Contratos.csproj" />
    <ProjectReference Include="..\..\Identidade\Intrega.Modulos.Identidade.Contratos\Intrega.Modulos.Identidade.Contratos.csproj" />
    <ProjectReference Include="..\..\Roteirizacao\Intrega.Modulos.Roteirizacao.Contratos\Intrega.Modulos.Roteirizacao.Contratos.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Intrega.TestesUnitarios" />
  </ItemGroup>
</Project>
