// <auto-generated />
using System;
using Intrega.Modulos.Rastreamento.Infraestrutura;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Intrega.Modulos.Rastreamento.Infraestrutura.Migracoes
{
    [DbContext(typeof(ContextoRastreamento))]
    [Migration("20261006210604_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("rastreamento")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Intrega.Modulos.Rastreamento.Dominio.AmostraDePosicao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<double?>("Direcao")
                        .HasColumnType("double precision");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("PrecisaoMetros")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("RegistradaEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("RotaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.Property<double?>("VelocidadeMetrosPorSegundo")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("RegistradaEm");

                    b.HasIndex("UsuarioId", "RegistradaEm");

                    b.ToTable("posicoes", "rastreamento");
                });

            modelBuilder.Entity("Intrega.Modulos.Rastreamento.Dominio.ConfiguracaoFinanceira", b =>
                {
                    b.Property<Guid>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("CustoFixoPorDia")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal?>("KmPorLitro")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal?>("PrecoDoCombustivelPorLitro")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal?>("ValorPorEntrega")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal?>("ValorPorPacote")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("UsuarioId");

                    b.ToTable("configuracoes_financeiras", "rastreamento");
                });

            modelBuilder.Entity("Intrega.Modulos.Rastreamento.Dominio.RegistroDeEntrega", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Marketplace")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Motivo")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTimeOffset>("OcorridoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ParadaId")
                        .HasColumnType("uuid");

                    b.Property<int>("QuantidadeDePacotes")
                        .HasColumnType("integer");

                    b.Property<string>("Resultado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid?>("RotaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId", "OcorridoEm");

                    b.ToTable("registros_de_entrega", "rastreamento");
                });
#pragma warning restore 612, 618
        }
    }
}
