// <auto-generated />
using System;
using Intrega.Modulos.Importacao.Infraestrutura;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Intrega.Modulos.Importacao.Infraestrutura.Migracoes
{
    [DbContext(typeof(ContextoImportacao))]
    partial class ContextoImportacaoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("importacao")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Intrega.Modulos.Importacao.Dominio.TrabalhoDeImportacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ConcluidaEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LinhasPendentes")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("LinhasProcessadas")
                        .HasColumnType("integer");

                    b.Property<string>("NomeDoArquivo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid?>("OrganizacaoId")
                        .HasColumnType("uuid");

                    b.Property<int>("ParadasCriadas")
                        .HasColumnType("integer");

                    b.Property<int>("PrecisamConfirmacao")
                        .HasColumnType("integer");

                    b.Property<Guid?>("RotaId")
                        .HasColumnType("uuid");

                    b.Property<int>("SemLocalizacao")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("TotalDeLinhas")
                        .HasColumnType("integer");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("UsuarioId", "CriadoEm");

                    b.ToTable("trabalhos", "importacao");
                });

            modelBuilder.Entity("Intrega.Modulos.Importacao.Dominio.TrabalhoDeImportacao", b =>
                {
                    b.OwnsMany("Intrega.Modulos.Importacao.Dominio.ErroDeLinha", "Erros", b1 =>
                        {
                            b1.Property<Guid>("TrabalhoDeImportacaoId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<int>("Linha");

                            b1.Property<string>("Mensagem")
                                .IsRequired();

                            b1.HasKey("TrabalhoDeImportacaoId", "__synthesizedOrdinal");

                            b1.ToTable("trabalhos", "importacao");

                            b1
                                .ToJson("erros")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("TrabalhoDeImportacaoId");
                        });

                    b.Navigation("Erros");
                });
#pragma warning restore 612, 618
        }
    }
}
